### ISSUE TITLE
[TroubleShooting] `ExpChart` 그래프가 그려지지 않는 문제

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#159]
### 원인
경험치 계산 결과가 `NaN`으로 나온다

➡ 왜냐면 `maximumExp` 값이 `undefined`다

➡ 왜냐면 서버 데이터 중 `status`의 `maximumExp`가 `maxExp`로 이름이 바뀌었기 때문에 `status`에서 `maximumExp`를 찾지 못했다

### TODO
- [x] `StatusType` 수정
- [x] `ExpChart` 코드 수정

**Comment by nijuy** [comment]
반대합니다
사유: 수정 끝내놓고 올린 이슈입니다~ 짜잔~
이거보다 좀 더 수정범위가 넓은 작업을 방금 끝내서!!! 그거 PR 올리고 이것도 바로 이어서 올리려고 했아요!!!!!

대신 다음부터 이름 바뀌면 푸론트도 알려주세요 아무래도 갑자기 안되니까 식은땀이.

**Comment by 0chil** [comment]
짜잔 ~
죄송합니다 maximumExp로 하기로 했다는걸 까먹었네요 ㅎㅎ;
다음부턴 API를 한번 더 확인하도록 하겠습니디ㅏ~

**Comment by nijuy** [comment]
네에 저도 담부턴 선수정 후이슈말고 먼저 전달하겠습니다!!!!!!!!
