### ISSUE TITLE
[TroubleShooting] LobbyScreen의 SettingPopup에서 pause 이벤트가 발생하는 문제

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#243]
## SettingPopup이 화면에 뜨는 경우

1) LobbyScreen -> 게임 진행 중이 아니므로 api 요청 쏠 필요 없음
2) GameScreen -> 서버에게 게임 세션이 일시정지임을 알려야함

`SettingPopup`에서는 **IN_PROGRESS일 때만** 요청을 보내도록 되어있기 때문에 사실 1, 2를 잘 구분하고 있음

문제는

1. 게임을 시작하고 (IN_PROGRESS) 
2. 종료되기 전에 새로고침하면
➡ game state가 IN_PROGRESS로 남아있는다는 거임

## 이로 인해 발생하는 문제

위 문제가 발생했을 경우, 1에서도 api 요청을 보내게 됨 (IN_PROGRESS니까)
서버가 보기엔 그 게임 세션은 진행 중인 상태가 아니기 때문에, 에러를 던짐

![pause_error](https://github.com/snack-game/front/assets/87255462/c39afbce-3be5-4250-9048-036817e59280)

여기서 `재시도` 누르면 팝업이 열린 상태 그대로 LobbyScreen이 떠서 겹쳐보임 ㅠㅠ 흑흑

![image](https://github.com/snack-game/front/assets/87255462/b491aced-d0b9-49c7-ad8f-c95db31a76c1)

**Comment by dev-dong-su** [comment]
홀리 몰리 어느정도 예외를 처리 했다고 생각했는데 이런 허점이 있었군요..

**Comment by 0chil** [comment]
요거 제가 올릴 PR에서 해결됩니다!

**Comment by nijuy** [comment]
과카몰리......... 확인했스빈다!!!!!!
