### ISSUE TITLE
[TroubleShooting] 점수 모달을 띄운 상태로 다른 탭으로 이동할 수 있는 문제 

### ISSUE THREAD

**Issue by 0chil** [snack-game/front#257]
<img src="https://github.com/user-attachments/assets/5f230e46-dbc2-495a-ba83-f5aacf73ebe2" width="300">

이 상태에서 랭킹을 누르면 점수 모달이 떠있는 상태로 이동됩니다!
BottomNav의 z-index를 낮춰서 해결할 수 있을 것 같은데요.
@dev-dong-su @nijuy 현재 `z-index: 999`인데는 숨겨진 의도가 있을까요?

**Comment by nijuy** [comment]
숨겨진 의도...........는 아마도 없고 제일 위에 띄우기 위해 999로 설정하신 거 같아용
오전에 올려주신 이슈 포함해서 모두 확인했습니다!!!!!!!! 꼼꼼땡칠 줄여서 꼼칠
