### ISSUE TITLE
[TroubleShooting] 게스트의 랭킹 페이지가 잘못 그려지는 문제

### ISSUE THREAD

**Issue by 0chil** [snack-game/front#268]
<img src="https://github.com/user-attachments/assets/70dca90f-e125-4149-b226-ee35131aeda9" width="300">

빠른 대응 항상 감사드립니다.
랭킹이 없을 때 1,2,3등이 너무 위에있는 문제가 있네요 :)

**Comment by nijuy** [comment]
끼약
당장해결하겠습니다
