### ISSUE TITLE
[TroubleShooting] 게임 재시작시 사과가 증발하는 문제

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#280]
## 재현 방법

1. 게임 실행
2. 게임 결과 모달의 `재시작` 클릭
3. 짜잔~......

| 첫번째 재시작 | 두번째 재시작 |
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/757ab7e9-d3a8-4390-a356-b0f6acabcd3a)|![image](https://github.com/user-attachments/assets/db2e161a-d072-46e9-8c40-dcb4d855f017)|
|1개 증발|2개 증발|

**Comment by 0chil** [comment]
@dev-dong-su 짜잔형 해결해주세요 ㅠㅠ
