### ISSUE TITLE
[Refactoring] Auth 페이지 제거

### ISSUE THREAD

**Issue by 0chil** [snack-game/front#281]
1. 앱에서 해당 페이지를 직접 구현했으므로, 유저가 해당 페이지에 접근할 일이 없습니다.
2. #272 에 의해 앱에서도 OAuth를 요청할 수 있게 되었습니다.

모달로 로그인을 요구하는 방식이 더 투명하고 유저에게 적은 스트레스를 주므로, 기존 방식으로 회귀할 필요가 있습니다.
게다가 이 페이지는 데스크톱에서 잘못 표현되고 있으므로 제거하는게 좋을 것 같습니다.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/d1dbc755-8a0b-4284-8d9b-302d8ead9485">

**Comment by nijuy** [comment]
> 앱에서 해당 페이지를 직접 구현했으므로, 유저가 해당 페이지에 접근할 일이 없습니다.

이그젝틀리입니다 해당 페이지는 웹에서만 사용되고 있는데요! 본문에 적어주신 이유로 삭제하는 게 맞겠네요.
UI 깨짐 확인까지 감사합니다감사하빈다.........ㅠㅠ

아래는 작업 들어가기 전에 어떻게 수정할지 생각해본 내용인데요!
**제가 확인을 늦게 해서,,, 미리 공유드리고자 적는 내용이고, PR에 같은 내용이 들어갈 거라 사실 나중에 읽어보셔두 됩니다!!!!!** 




### 현재 Auth 페이지의 쓰임

`SettingPage` : 설정 페이지 컴포넌트 / 로그아웃 후 `PATH.AUTH`로 이동

`TopBar` : 설정 페이지에 쓰이는 컴포넌트 / `user.id`가 없다면 해당 페이지 접근이 불가한 케이스이므로 `PATH.AUTH`로 이동

생각해보니 특정 페이지에 대한 접근 제어를 컴포넌트에 두는 게 약간 어색하게 느껴지네요 (그림을 그려봤는데용.. 뭔말알?!?!?!)

![image](https://github.com/user-attachments/assets/78821111-0ccf-4bc2-8483-4d403fcc138e)

### 수정 방향

`SettingPage` : 로그아웃 후 랜딩 페이지 or 게임 페이지로 이동
  
  - 어디론가 이동을 하긴 해야 하는데 (마치 네이버 메일함에서 로그아웃하면 네이버 메인으로 가듯이,,,)
    현재 데스크톱에서 비로그인 상태로 게임 시작했을 때 대응이 안 되어있어서
    로그아웃 후 랜딩 페이지로 이동하게 해두고, 위 내용 대응 끝나면 게임 페이지로 이동하게끔 해볼 예정

`TopBar` : 접근 제어 로직 삭제

---

**예상 질문(?): 그러면 SettingPage에 대한 접근 제어는 어디서 하냐?** -> `UserPage`의 접근 제어 로직을 상위로 분리해서 재사용

```tsx
  useEffect(() => {
    if (!userInfo.id) { // 로그인 안 한 사용자면
      openModal({
        children: <Auth />, // 로그인 모달을 띄운다
        handleOutsideClick: () => {
          navigate(-1);
        },
      });
    }
  }, []);
```

**Comment by 0chil** [comment]
@nijuy 뭔말알잘딱깔센 했습니다!

추가로 '비로그인 상태에서 게임 시작'은 게스트 로그인시킨 후 진행하면 어떨까요?
이 방식은 기존 사과게임에서 사용하던 방법이자 게스트 로그인의 목적이기도 합니다.

**Comment by nijuy** [comment]
저도 그것을 생각했읍니다 독심술사 땡

**Comment by 0chil** [comment]
넵 저는 운영 배포 및 발표를 준비하고 있겠습니다!
