### ISSUE TITLE
[TroubleShooting] 게스트 로그인이 불안정한 문제

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#290]
## 문제 상황

- 플랫폼: 웹 (앱은 로그인 화면 자체 구현해둠. 로비 화면이 떴다는 건 무조건 이미 로그인 한 상태임)
- 시점: 게임을 시작했을 때
- 문제:
  - 로그인 했는데 게스트 로그인이 진행되거나
  - 비로그인 상태인데 게스트 로그인이 되지 않음

### 문제 상황의 동작 과정

1. 로그아웃하면 `userInfo` 리셋 (`userInfo.id = undefined`) & 토큰 삭제
2. `handleNonLoggedInUser`에서 `userInfo.id = undefined`면 게스트 로그인을 수행함
3. (2)의 함수에서 `userInfo`가 로그아웃 전 값으로 남아있어서 문제 발생
4. 단, 토큰은 정상적으로 삭제된 상황이기 때문에 게임 시작 API에서 토큰 에러가 나서 게임 진행이 안됨

### 앱스크린을 재사용 하면서 발생하는 상황 같음

- 앱스크린의 재사용 과정
   - 1. `SnackGameBase`가 렌더링 될 때 `application`이 초기화 된다
   - 2. 초기화에 사용하는 인자 `initializeAppScreens`는 스크린 인스턴스를 생성해 `appScreenPool`에 넣는 역할
   - 3. `initializeApplication`에서 `initializeAppScreens`는 `!pixiValue.assetsInit`일 때만 수행된다 (매번 수행 아님)
   - 4. 에셋 초기화가 끝난 이후에는 처음 생성한 스크린 인스턴스를 재사용한다

- 재사용되는 `LobbyScreen`에서 들고 있는 `handleNonLoggedInUser`
 
  함수가 생성되는 시점의 userInfo.id를 클로저로 캡쳐 ➡️ userInfo 값이 외부에 의해 바뀌어도 반영되지 않음

흠. 그럼 함수 안에서 로컬 스토리지 메서드를 그대로 써야 하나? 구리다

### 그렇게 생각하는 이유

`SnackGameBase`가 렌더링 될 때마다 `userInfo`를 찍어보니까 최신값으로 잘 반영되어있는데
`handleNonLoggedInUser` 내에서만 과거 값인 점에서.... 위와 같이 생각함

**Comment by 0chil** [comment]
클로저로 인한 문제일 가능성이 있겠네요.
저도 이번주에 한번 살펴보겠습니다

**Comment by 0chil** [comment]
저도 연구를 해봤는데, 짚어주신 원인이 맞았습니다.
> 재사용되는 LobbyScreen에서 들고 있는 handleNonLoggedInUser
> 함수가 생성되는 시점의 userInfo.id를 클로저로 캡쳐 ➡️ userInfo 값이 외부에 의해 바뀌어도 반영되지 않음

`SnackGameBase` 내에 다음과 같은 useEffect 훅을 사용했을 때, 유저 정보가 정상적으로 바뀌는 것을 확인했으나, 
```ts
  useEffect(() => {
    console.log("userInfo Changed: ", userInfo);
  }, [userInfo]);
```
`handleNonLoggedInUser`는 여전히 기존 정보를 보여주더라구요.

갖가지 방법 (useCallback, useRef.. )들을 써봤지만 잘 안되네요 ㅠㅠ
땜빵하는 방법으로는 말씀해주신 localStorage 혹은 event를 사용한 방법이 떠오르는데.. 둘 다 좋은 방법은 아닌 것 같아요.
우선 Snackgame Biz를 하면서 다시 고민해보겠습니다

**Comment by 0chil** [comment]
localStorage는 디스크에 쓰는거라서 살~짝 우려되는 부분이 있네요
이벤트 리스너 + useEffect로 우선 해결해보면 어떨까요?

**Comment by nijuy** [comment]
> localStorage는 디스크에 쓰는거라서 살~짝 우려되는 부분이 있네요 (기록/삭제 등 관리 포인트가 늘어남)

뭔가... `로그인 여부를 나타내는 값을 localstorage에 추가하고, 그걸 사용하자` 는 의미로 받아들여진 거 같아!! 해명합니다!!!
전역 상태(userState)를 window.localStorage()로 조회하는 방향을 제안해본 거였어요
이미 이걸로 이해하신 거였다면 머쓱하네요 스킵 해주십숑

```ts
  const handleNonLoggedInUser = async () => {
    const isLoggedIn = JSON.parse(window.localStorage.getItem(ATOM_KEY.USER_PERSIST) || '{}').userState;
    if (!isLoggedIn) await guestMutation.mutateAsync();
  };
```

---

> 이벤트 리스너 + useEffect로 우선 해결해보면 어떨까요?

저 여기 잘 이해가 안 가는데 조금만 더 설명해주실 수 있을까요 🥲 헬프 도움

**Comment by 0chil** [comment]
ㅏㅏㅏㅏㅏ.. 이런 깊은 뜻이...
제가 말도 안들어보고 단정해버렸네요 😇🙇
이런 방식이라면 최소한의 변경으로 목적 달성이 가능할 것 같습니다.
이렇게 해두고 더 나은 방법을 찾아보면 되겠네요!

EL+useEffect는 무슨 말이냐 하면요..
`handleNonLogin()` 시점에 A라는 이벤트를 쏘고,
그걸 `SnackgameBase`에서 받아서 처리하자는 것이었습니다:
```js
useEffect(()=> {
addEventListener('A', e=> xxx(userInfo));
return ()=>removeEL();
}, [userInfo]);
```
이런식으로 userInfo 변경에 맞춰서 등록/해제를 반복하면서 말이죠..
좋은 방법은 절대 아닙니다 😅😅

보리보리쌀이 얘기해준 방법이 훨씬 더 좋은 것 같아요 (변경 전파가 적음 + 간단)
말씀해주신 방법으로 해보면 좋겠네요💯

**Comment by nijuy** [comment]
아녜요 `로그인 정보를 확인한다`고 하니까 기존 전역 상태 말고 다른 값을 만들겠다는 것처럼 보임,, 저의 실수 ~ (〃⌒∇⌒〃)ゝ 

핸드폰으로 한땀한땀 쓴 코드라니 귀하네요............ 설명에 감사드리며!!! 그렇다면 위 방법대로 수정해서 바로 머지하겠습니다
(설명할 때 쓴 코드 블럭 내용 외에 다른 수정되는 곳이 없어서요!)
