### ISSUE TITLE
[Feature] 랜딩 페이지 앱 출시 섹션 추가

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#312]
생각해보니 https://snackga.me/ 에는 앱 관련 얘기가 하나또 없어서 앱 홍보용 섹션을 하나 넣으려고 함

**Comment by 0chil** [comment]
좋습니다..!
[Smart App banner](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners)도 관심있다면 추천드립니다 ㅎㅎ

**Comment by nijuy** [comment]
> [Smart App banner](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners)도 관심있다면 추천드립니다 ㅎㅎ

이거 뭐라고 부르는지 궁금했는데..... 필요한 거 딱 가져다 주는 게 도라에몽 같아요
난 진구

**Comment by 0chil** [comment]
![EC8BA0+EB8F84EB9DBCEC9790EBAABD+21-22+poster](https://github.com/user-attachments/assets/16f7a66f-fcb0-4fb5-85c1-0911987bdd19)
