### ISSUE TITLE
[Feature] 공지 페이지 고도화

### ISSUE THREAD

**Issue by 0chil** [snack-game/front#332]
페이지: https://notice.snackga.me/
RSS: https://notice.snackga.me/index.xml

요청해주신 iframe은 허용해두었고, rss를 이용해 원하는 형태로 구현 가능하실거라고 생각합니다.
공지사항 출처는 노션 - 스낵게임 블로그 - 공지사항에 적은 글이며, 정각 기준 30분마다 갱신됩니다!

**Comment by nijuy** [comment]
확인했읍니다 최고으 개발자네요 ദ്ദി˶﻿ˆ꒳ˆ˵)
